### ISSUE TITLE
Group array does not work

### ISSUE THREAD

**Issue by Pshatsillo** [jeroenhendricksen/node-red-contrib-openhab3#16]
HI, **groupNames** in rest not the same as **members**. So groups array will be always 0 if remove members parser in 726 string... That's exactly what i have now.... `type: "Group" groups: array[0]`

**Comment by jeroenhendricksen** [comment]
Thank you for your issue. What exactly do I need to change? Do I need to replace members with groupNames? I'm confused, because I tested this in my test-setup (with OpenHAB 3) and it seemed to work.

**Comment by Pshatsillo** [comment]
REST json of Group looks like this:

```
{
  "members": [
    {
      "link": "http://192.168.0.1:8080/rest/items/kamilRoomKlimatGRP",
      "state": "50.29",
      "stateDescription": {
        "step": 1,
        "pattern": "%s",
        "readOnly": true,
        "options": []
      },
      "type": "Number",
      "name": "HumidityKamilRoomZigbee",
      "label": "Влажность в комнате Камиля (Zigbee)",
      "category": "humidity",
      "tags": [
        "Sensor"
      ],
      "groupNames": [
        "KamilGRP",
        "Temperature",
        "kamilRoomKlimatGRP"
      ]
    },
    {
      "link": "http://192.168.0.1:8080/rest/items/kamilRoomKlimatGRP",
      "state": "22.0",
      "type": "Number",
      "name": "SetpointTemperatureKamilRoom",
      "label": "Установка температуры в комнате Камиля",
      "category": "temperature",
      "tags": [],
      "groupNames": [
        "SetpointsGRP",
        "kamilRoomKlimatGRP"
      ]
    }
  ],
  "link": "http://192.168.0.1:8080/rest/items/kamilRoomKlimatGRP",
  "state": "NULL",
  "editable": true,
  "type": "Group",
  "name": "kamilRoomKlimatGRP",
  "label": "Климат в комнате камиля",
  "category": "climate",
  "tags": [],
  "groupNames": [
    "KamilGRP"
  ]
}
```
as we can see, items array is under members tag. groupNames tag shows us groups where item is included

**Comment by Pshatsillo** [comment]
as i see, you remove from  [here](https://github.com/jeroenhendricksen/node-red-contrib-openhab3/blob/a60d6aa14482878d2995a2207a5ac0dd0251d694/77-openhab2.js#L722 ) code```
 if(type == "Group"){
                        let grpMembers = {};
                        var membArr = JSON.parse(body).members;
                        membArr.forEach(val => {
                            grpMembers = { ...grpMembers, [val.name]: val };
                        });
                        msg.group = grpMembers;
                    }
```

which filled exactly items array

**Comment by jeroenhendricksen** [comment]
> as i see, you remove from [here](https://github.com/jeroenhendricksen/node-red-contrib-openhab3/blob/a60d6aa14482878d2995a2207a5ac0dd0251d694/77-openhab2.js#L722) code
> 
> ```
>  if(type == "Group"){
>                         let grpMembers = {};
>                         var membArr = JSON.parse(body).members;
>                         membArr.forEach(val => {
>                             grpMembers = { ...grpMembers, [val.name]: val };
>                         });
>                         msg.group = grpMembers;
>                     }
> ```
> 
> which filled exactly items array
> 
> for items post there groupnames is perfect idea, but for groups it must be array of items i think. maybe you should change [this line](https://github.com/jeroenhendricksen/node-red-contrib-openhab3/blob/a60d6aa14482878d2995a2207a5ac0dd0251d694/77-openhab2.js#L712) to
> 
> ```
> var groupNames = {};
>  if(type == "Group"){
>                         var membArr = JSON.parse(body).members;
>                         membArr.forEach(val => {
>                             groupNames = { ...grpMembers, [val.name]: val };
>                         });
>                        
>    } else {
>  groupNames = JSON.parse(body).groupNames;
> }
> ```

Ah, now I understand what you mean. Thank you for the explanation. I indeed tested the code for items, not for groups. I'll have a look at your proposed code. Also, if I remember correctly I tried your proposed code at first, bit I couldn't get the `groupNames = { ...grpMembers, [val.name]: val };` to work in javascript, but if that is the case I'll ask for your help.

**Comment by jeroenhendricksen** [comment]
I've added code that exposes member data via the msg.member property for the get2 node. 

https://github.com/jeroenhendricksen/node-red-contrib-openhab3/pull/17

Please let me know if this helps you out!

**Comment by Pshatsillo** [comment]
https://github.com/Pshatsillo/node-red-contrib-openhab3/blob/eed76f537f70e958e59ac54de3008ca3f5c29696/77-openhab2.js#L720 Please change **groupNames**  to **grpMembers** and everything will be fine :)

**Comment by jeroenhendricksen** [comment]
> https://github.com/Pshatsillo/node-red-contrib-openhab3/blob/eed76f537f70e958e59ac54de3008ca3f5c29696/77-openhab2.js#L720

I replaced `groupNames` to `grpMembers` on L720, so it looks like this:

```
if (type == "Group") {
    let grpMembers = {};
    var membArr = JSON.parse(body).members;
    membArr.forEach(val => {
        grpMembers = { ...grpMembers, [val.name]: val };
    });
    msg.members = groupNames;
}
```

... but that throws an exception:

```
22 Jul 07:21:27 - [red] Uncaught Exception:
22 Jul 07:21:27 - ReferenceError: groupNames is not defined
    at /node-red-contrib-openhab3/77-openhab2.js:722:39
    at Request._callback (/node-red-contrib-openhab3/77-openhab2.js:271:21)
    at Request.self.callback (/node-red-contrib-openhab3/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/node-red-contrib-openhab3/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/node-red-contrib-openhab3/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
```

What exactly do you want me to change? I've tested the above commit locally and it seemed to work as intended. Please let me know.

**Comment by jeroenhendricksen** [comment]
I think I understand your intention. Do you like me to change the code to this?

```
if (type == "Group") {
  let grpMembers = {};
  var membArr = JSON.parse(body).members;
  membArr.forEach(val => {
      grpMembers = { ...grpMembers, [val.name]: val };
  });
  msg.members = grpMembers;
  }
```

**Comment by Pshatsillo** [comment]
Yes! Exactly! We must assign grpMembers to msg.members when we filled
array. Thank you!

чт, 22 июл. 2021 г., 10:28 Jeroen Hendricksen ***@***.***>:

**Comment by Pshatsillo** [comment]
Yes! It works perfect now! Thank You!
