### ISSUE TITLE
openhab2-in2 does not update the status

### ISSUE THREAD

**Issue by massimilianocasini** [jeroenhendricksen/node-red-contrib-openhab3#37]
Update the node status only when the flow starts.
node-red-contrib-openhab3-1.3.45@openHAB 3.3.0.M7

**Comment by jeroenhendricksen** [comment]
> Update the node status only when the flow starts. node-red-contrib-openhab3-1.3.45@openHAB 3.3.0.M7

I've been thinking about implementing this (or likewise) behaviour by looking at the openHAB "system start level" value. Only when this value is 100, I would send any updates, ensuring previous OH items states are already reloaded. However, it seems this value is not available via the API (via a GET request). You can retrieve the value by typing `system:start-level` at the openhab karaf console.

**Comment by jeroenhendricksen** [comment]
I figured the api shows systeminfo, but it doesn't show start-level:

```
curl http -XGET -H "Authorization: Bearer oh.nodered.Q1yGmLQWYwEG7xlKQDZq71HQahc2BnGL8HgVOWME46uJdbNcugEF7nA5If4BtvApJJUCmymnSU3RlwaODNA" http://localhost:55002/rest/systeminfo
curl: (6) Could not resolve host: http
{"systemInfo":{"configFolder":"/openhab/conf","userdataFolder":"/openhab/userdata","logFolder":"/openhab/userdata/logs","javaVersion":"11.0.13","javaVendor":"Azul Systems, Inc.","javaVendorVersion":"Zulu11.52+13-CA","osName":"Linux","osVersion":"5.10.104-linuxkit","osArchitecture":"amd64","availableProcessors":4,"freeMemory":54562384,"totalMemory":171966464}}%
```

I couldn't find any other endpoints showing this information either...

**Comment by massimilianocasini** [comment]
That is precisely what I meant.

Inviata da Android
________________________________

**Comment by rathi66** [comment]
I just noticed the same thing after upgrading to OH 3.3.

**Comment by miccgn** [comment]
Seems to work fine now with 1.4.2. Thank you very much!

**Comment by jeroenhendricksen** [comment]
> Seems to work fine now with 1.4.2. Thank you very much!

Great to hear. It was issue #38 that was actually the same, but I failed to notice that. I'm glad its fixed now!

**Comment by massimilianocasini** [comment]
Thank's to you. I can confirm that the problem is solved.

**Comment by nodiaque** [comment]
I'd like to reopen this problem. I'm currently with 1.4.6 and none of my node are updating. There's no error in the nodered debug window and the log file from the docker in unraid doesn't show error that are current. I have error dating 3 hours ago that are connection error to my openhab server (which I rebooted because of other binding issue).

**Comment by nodiaque** [comment]
I've open issue #50 and I'll update in that thread.
